use prjcombine_interconnect::{bels, db::BelSlotId};

use crate::tslots;

bels![
    INT: tslots::INT,
    SLICE0: tslots::BEL,
    SLICE1: tslots::BEL,
    SLICE2: tslots::BEL,
    SLICE3: tslots::BEL,
    BRAM: tslots::BEL,
    FIFO: tslots::BEL,
    BRAM_F: tslots::BEL,
    BRAM_H0: tslots::BEL,
    BRAM_H1: tslots::BEL,
    BRAM_ADDR: tslots::BEL,
    PMVBRAM: tslots::HCLK_BEL,
    PMVBRAM_NC: tslots::HCLK_BEL,
    DSP0: tslots::BEL,
    DSP1: tslots::BEL,
    TIEOFF_DSP: tslots::BEL,
    IN_FIFO: tslots::BEL_B,
    OUT_FIFO: tslots::BEL_B,
    ILOGIC0: tslots::BEL,
    ILOGIC1: tslots::BEL,
    OLOGIC0: tslots::BEL,
    OLOGIC1: tslots::BEL,
    IODELAY0: tslots::BEL,
    IODELAY1: tslots::BEL,
    IDELAY0: tslots::BEL,
    IDELAY1: tslots::BEL,
    ODELAY0: tslots::BEL,
    ODELAY1: tslots::BEL,
    IOB0: tslots::BEL,
    IOB1: tslots::BEL,
    IOI: tslots::BEL,
    DCM0: tslots::BEL,
    DCM1: tslots::BEL,
    PLL: tslots::BEL,
    CMT: tslots::BEL,
    CMT_A: tslots::BEL,
    CMT_B: tslots::BEL,
    CMT_C: tslots::BEL,
    CMT_D: tslots::BEL,
    CCM: tslots::BEL,
    PMCD0: tslots::BEL,
    PMCD1: tslots::BEL,
    DPM: tslots::BEL,
    MMCM0: tslots::BEL,
    MMCM1: tslots::BEL,
    PPR_FRAME: tslots::BEL,
    PMVIOB: tslots::BEL,
    PHASER_IN0: tslots::BEL,
    PHASER_IN1: tslots::BEL,
    PHASER_IN2: tslots::BEL,
    PHASER_IN3: tslots::BEL,
    PHASER_OUT0: tslots::BEL,
    PHASER_OUT1: tslots::BEL,
    PHASER_OUT2: tslots::BEL,
    PHASER_OUT3: tslots::BEL,
    PHASER_REF: tslots::BEL,
    PHY_CONTROL: tslots::BEL,
    BUFMRCE0: tslots::BEL,
    BUFMRCE1: tslots::BEL,
    PPC: tslots::BEL,
    EMAC: tslots::BEL,
    PCIE: tslots::BEL,
    PCIE3: tslots::BEL,
    SYSMON: tslots::BEL,
    IPAD_VP: tslots::BEL,
    IPAD_VN: tslots::BEL,
    GT11_0: tslots::BEL,
    GT11_1: tslots::BEL,
    GT11CLK: tslots::BEL,
    GTP_DUAL: tslots::BEL,
    GTX_DUAL: tslots::BEL,
    GTX0: tslots::BEL,
    GTX1: tslots::BEL,
    GTX2: tslots::BEL,
    GTX3: tslots::BEL,
    GTH_QUAD: tslots::BEL,
    GTP_COMMON: tslots::BEL,
    GTX_COMMON: tslots::BEL,
    GTH_COMMON: tslots::BEL,
    GTP_CHANNEL: tslots::BEL,
    GTX_CHANNEL: tslots::BEL,
    GTH_CHANNEL: tslots::BEL,
    BUFDS0: tslots::BEL,
    BUFDS1: tslots::BEL,
    CRC32_0: tslots::BEL,
    CRC32_1: tslots::BEL,
    CRC32_2: tslots::BEL,
    CRC32_3: tslots::BEL,
    CRC64_0: tslots::BEL,
    CRC64_1: tslots::BEL,
    IPAD_CLKP0: tslots::BEL,
    IPAD_CLKN0: tslots::BEL,
    IPAD_CLKP1: tslots::BEL,
    IPAD_CLKN1: tslots::BEL,
    IPAD_RXP0: tslots::BEL,
    IPAD_RXN0: tslots::BEL,
    IPAD_RXP1: tslots::BEL,
    IPAD_RXN1: tslots::BEL,
    IPAD_RXP2: tslots::BEL,
    IPAD_RXN2: tslots::BEL,
    IPAD_RXP3: tslots::BEL,
    IPAD_RXN3: tslots::BEL,
    OPAD_TXP0: tslots::BEL,
    OPAD_TXN0: tslots::BEL,
    OPAD_TXP1: tslots::BEL,
    OPAD_TXN1: tslots::BEL,
    OPAD_TXP2: tslots::BEL,
    OPAD_TXN2: tslots::BEL,
    OPAD_TXP3: tslots::BEL,
    OPAD_TXN3: tslots::BEL,
    BUFGCTRL0: tslots::BEL,
    BUFGCTRL1: tslots::BEL,
    BUFGCTRL2: tslots::BEL,
    BUFGCTRL3: tslots::BEL,
    BUFGCTRL4: tslots::BEL,
    BUFGCTRL5: tslots::BEL,
    BUFGCTRL6: tslots::BEL,
    BUFGCTRL7: tslots::BEL,
    BUFGCTRL8: tslots::BEL,
    BUFGCTRL9: tslots::BEL,
    BUFGCTRL10: tslots::BEL,
    BUFGCTRL11: tslots::BEL,
    BUFGCTRL12: tslots::BEL,
    BUFGCTRL13: tslots::BEL,
    BUFGCTRL14: tslots::BEL,
    BUFGCTRL15: tslots::BEL,
    BUFGCTRL16: tslots::BEL,
    BUFGCTRL17: tslots::BEL,
    BUFGCTRL18: tslots::BEL,
    BUFGCTRL19: tslots::BEL,
    BUFGCTRL20: tslots::BEL,
    BUFGCTRL21: tslots::BEL,
    BUFGCTRL22: tslots::BEL,
    BUFGCTRL23: tslots::BEL,
    BUFGCTRL24: tslots::BEL,
    BUFGCTRL25: tslots::BEL,
    BUFGCTRL26: tslots::BEL,
    BUFGCTRL27: tslots::BEL,
    BUFGCTRL28: tslots::BEL,
    BUFGCTRL29: tslots::BEL,
    BUFGCTRL30: tslots::BEL,
    BUFGCTRL31: tslots::BEL,
    GIO_S: tslots::BEL,
    GIO_N: tslots::BEL,
    GCLK_BUF: tslots::BEL,
    BUFG_MGTCLK_S: tslots::BEL,
    BUFG_MGTCLK_N: tslots::BEL,
    BUFG_MGTCLK_S_HROW: tslots::BEL,
    BUFG_MGTCLK_N_HROW: tslots::BEL,
    BUFG_MGTCLK_S_HCLK: tslots::BEL,
    BUFG_MGTCLK_N_HCLK: tslots::BEL,
    BUFHCE_W0: tslots::BEL,
    BUFHCE_W1: tslots::BEL,
    BUFHCE_W2: tslots::BEL,
    BUFHCE_W3: tslots::BEL,
    BUFHCE_W4: tslots::BEL,
    BUFHCE_W5: tslots::BEL,
    BUFHCE_W6: tslots::BEL,
    BUFHCE_W7: tslots::BEL,
    BUFHCE_W8: tslots::BEL,
    BUFHCE_W9: tslots::BEL,
    BUFHCE_W10: tslots::BEL,
    BUFHCE_W11: tslots::BEL,
    BUFHCE_E0: tslots::BEL,
    BUFHCE_E1: tslots::BEL,
    BUFHCE_E2: tslots::BEL,
    BUFHCE_E3: tslots::BEL,
    BUFHCE_E4: tslots::BEL,
    BUFHCE_E5: tslots::BEL,
    BUFHCE_E6: tslots::BEL,
    BUFHCE_E7: tslots::BEL,
    BUFHCE_E8: tslots::BEL,
    BUFHCE_E9: tslots::BEL,
    BUFHCE_E10: tslots::BEL,
    BUFHCE_E11: tslots::BEL,
    CLK_HROW: tslots::HROW,
    CLK_IOB: tslots::CLK,
    CLK_DCM: tslots::CLK,
    CLK_CMT: tslots::CLK,
    CLK_MGT: tslots::CLK,
    HCLK_BRAM_MGT: tslots::CLK,
    BRKH_GTX: tslots::HCLK_BEL,
    HCLK_GTX: tslots::BEL,
    HCLK_GTH: tslots::BEL,
    MGT_BUF: tslots::CLK,
    BSCAN0: tslots::BEL,
    BSCAN1: tslots::BEL,
    BSCAN2: tslots::BEL,
    BSCAN3: tslots::BEL,
    ICAP0: tslots::BEL,
    ICAP1: tslots::BEL,
    STARTUP: tslots::BEL,
    CAPTURE: tslots::BEL,
    JTAGPPC: tslots::BEL,
    PMV0: tslots::BEL,
    PMV1: tslots::BEL,
    DCIRESET: tslots::BEL,
    FRAME_ECC: tslots::BEL,
    USR_ACCESS: tslots::BEL,
    DNA_PORT: tslots::BEL,
    KEY_CLEAR: tslots::BEL,
    EFUSE_USR: tslots::BEL,
    CFG_IO_ACCESS: tslots::BEL,
    PMV2: tslots::BEL,
    PMV2_SVT: tslots::BEL,
    MTBF2: tslots::BEL,
    HCLK_IOI: tslots::HCLK_BEL,
    IOCLK: tslots::HCLK_BEL,
    RCLK: tslots::HCLK_BEL,
    HCLK_DCM_HROW: tslots::HCLK_BEL,
    HCLK_DCM: tslots::HCLK_BEL,
    HCLK_DCM_S: tslots::HCLK_BEL,
    HCLK_DCM_N: tslots::HCLK_BEL,
    HCLK_CMT: tslots::HCLK_CMT,
    HCLK_CMT_HCLK: tslots::HCLK_CMT,
    HCLK_CMT_GIOB: tslots::HCLK_CMT,
    BUFR0: tslots::HCLK_BEL,
    BUFR1: tslots::HCLK_BEL,
    BUFR2: tslots::HCLK_BEL,
    BUFR3: tslots::HCLK_BEL,
    BUFIO0: tslots::HCLK_BEL,
    BUFIO1: tslots::HCLK_BEL,
    BUFIO2: tslots::HCLK_BEL,
    BUFIO3: tslots::HCLK_BEL,
    BUFO0: tslots::HCLK_BEL,
    BUFO1: tslots::HCLK_BEL,
    IDELAYCTRL: tslots::HCLK_BEL,
    DCI: tslots::HCLK_BEL,
    HCLK: tslots::HCLK,
    HCLK_QBUF: tslots::HROW,
    HCLK_W: tslots::HCLK,
    HCLK_E: tslots::HCLK,
    INT_LCLK_W: tslots::CLK,
    INT_LCLK_E: tslots::CLK,
    GLOBALSIG: tslots::HCLK,
    GCLK_TEST_BUF_HROW_GCLK0: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK1: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK2: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK3: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK4: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK5: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK6: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK7: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK8: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK9: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK10: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK11: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK12: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK13: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK14: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK15: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK16: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK17: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK18: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK19: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK20: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK21: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK22: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK23: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK24: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK25: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK26: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK27: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK28: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK29: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK30: tslots::BEL,
    GCLK_TEST_BUF_HROW_GCLK31: tslots::BEL,
    CLK_REBUF: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S0: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S1: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S2: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S3: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S4: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S5: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S6: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S7: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S8: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S9: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S10: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S11: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S12: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S13: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S14: tslots::BEL,
    GCLK_TEST_BUF_REBUF_S15: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N0: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N1: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N2: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N3: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N4: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N5: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N6: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N7: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N8: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N9: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N10: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N11: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N12: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N13: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N14: tslots::BEL,
    GCLK_TEST_BUF_REBUF_N15: tslots::BEL,
    GCLK_TEST_BUF_HROW_BUFH_W: tslots::BEL,
    GCLK_TEST_BUF_HROW_BUFH_E: tslots::BEL,
    PS: tslots::BEL,
    HCLK_PS_S: tslots::BEL,
    HCLK_PS_N: tslots::BEL,
    IOPAD_DDRWEB: tslots::BEL,
    IOPAD_DDRVRN: tslots::BEL,
    IOPAD_DDRVRP: tslots::BEL,
    IOPAD_DDRA0: tslots::BEL,
    IOPAD_DDRA1: tslots::BEL,
    IOPAD_DDRA2: tslots::BEL,
    IOPAD_DDRA3: tslots::BEL,
    IOPAD_DDRA4: tslots::BEL,
    IOPAD_DDRA5: tslots::BEL,
    IOPAD_DDRA6: tslots::BEL,
    IOPAD_DDRA7: tslots::BEL,
    IOPAD_DDRA8: tslots::BEL,
    IOPAD_DDRA9: tslots::BEL,
    IOPAD_DDRA10: tslots::BEL,
    IOPAD_DDRA11: tslots::BEL,
    IOPAD_DDRA12: tslots::BEL,
    IOPAD_DDRA14: tslots::BEL,
    IOPAD_DDRA13: tslots::BEL,
    IOPAD_DDRBA0: tslots::BEL,
    IOPAD_DDRBA1: tslots::BEL,
    IOPAD_DDRBA2: tslots::BEL,
    IOPAD_DDRCASB: tslots::BEL,
    IOPAD_DDRCKE: tslots::BEL,
    IOPAD_DDRCKN: tslots::BEL,
    IOPAD_DDRCKP: tslots::BEL,
    IOPAD_PSCLK: tslots::BEL,
    IOPAD_DDRCSB: tslots::BEL,
    IOPAD_DDRDM0: tslots::BEL,
    IOPAD_DDRDM1: tslots::BEL,
    IOPAD_DDRDM2: tslots::BEL,
    IOPAD_DDRDM3: tslots::BEL,
    IOPAD_DDRDQ0: tslots::BEL,
    IOPAD_DDRDQ1: tslots::BEL,
    IOPAD_DDRDQ2: tslots::BEL,
    IOPAD_DDRDQ3: tslots::BEL,
    IOPAD_DDRDQ4: tslots::BEL,
    IOPAD_DDRDQ5: tslots::BEL,
    IOPAD_DDRDQ6: tslots::BEL,
    IOPAD_DDRDQ7: tslots::BEL,
    IOPAD_DDRDQ8: tslots::BEL,
    IOPAD_DDRDQ9: tslots::BEL,
    IOPAD_DDRDQ10: tslots::BEL,
    IOPAD_DDRDQ11: tslots::BEL,
    IOPAD_DDRDQ12: tslots::BEL,
    IOPAD_DDRDQ13: tslots::BEL,
    IOPAD_DDRDQ14: tslots::BEL,
    IOPAD_DDRDQ15: tslots::BEL,
    IOPAD_DDRDQ16: tslots::BEL,
    IOPAD_DDRDQ17: tslots::BEL,
    IOPAD_DDRDQ18: tslots::BEL,
    IOPAD_DDRDQ19: tslots::BEL,
    IOPAD_DDRDQ20: tslots::BEL,
    IOPAD_DDRDQ21: tslots::BEL,
    IOPAD_DDRDQ22: tslots::BEL,
    IOPAD_DDRDQ23: tslots::BEL,
    IOPAD_DDRDQ24: tslots::BEL,
    IOPAD_DDRDQ25: tslots::BEL,
    IOPAD_DDRDQ26: tslots::BEL,
    IOPAD_DDRDQ27: tslots::BEL,
    IOPAD_DDRDQ28: tslots::BEL,
    IOPAD_DDRDQ29: tslots::BEL,
    IOPAD_DDRDQ30: tslots::BEL,
    IOPAD_DDRDQ31: tslots::BEL,
    IOPAD_DDRDQSN0: tslots::BEL,
    IOPAD_DDRDQSN1: tslots::BEL,
    IOPAD_DDRDQSN2: tslots::BEL,
    IOPAD_DDRDQSN3: tslots::BEL,
    IOPAD_DDRDQSP0: tslots::BEL,
    IOPAD_DDRDQSP1: tslots::BEL,
    IOPAD_DDRDQSP2: tslots::BEL,
    IOPAD_DDRDQSP3: tslots::BEL,
    IOPAD_DDRDRSTB: tslots::BEL,
    IOPAD_MIO0: tslots::BEL,
    IOPAD_MIO1: tslots::BEL,
    IOPAD_MIO2: tslots::BEL,
    IOPAD_MIO3: tslots::BEL,
    IOPAD_MIO4: tslots::BEL,
    IOPAD_MIO5: tslots::BEL,
    IOPAD_MIO6: tslots::BEL,
    IOPAD_MIO7: tslots::BEL,
    IOPAD_MIO8: tslots::BEL,
    IOPAD_MIO9: tslots::BEL,
    IOPAD_MIO10: tslots::BEL,
    IOPAD_MIO11: tslots::BEL,
    IOPAD_MIO12: tslots::BEL,
    IOPAD_MIO13: tslots::BEL,
    IOPAD_MIO14: tslots::BEL,
    IOPAD_MIO15: tslots::BEL,
    IOPAD_MIO16: tslots::BEL,
    IOPAD_MIO17: tslots::BEL,
    IOPAD_MIO18: tslots::BEL,
    IOPAD_MIO19: tslots::BEL,
    IOPAD_MIO20: tslots::BEL,
    IOPAD_MIO21: tslots::BEL,
    IOPAD_MIO22: tslots::BEL,
    IOPAD_MIO23: tslots::BEL,
    IOPAD_MIO24: tslots::BEL,
    IOPAD_MIO25: tslots::BEL,
    IOPAD_MIO26: tslots::BEL,
    IOPAD_MIO27: tslots::BEL,
    IOPAD_MIO28: tslots::BEL,
    IOPAD_MIO29: tslots::BEL,
    IOPAD_MIO30: tslots::BEL,
    IOPAD_MIO31: tslots::BEL,
    IOPAD_MIO32: tslots::BEL,
    IOPAD_MIO33: tslots::BEL,
    IOPAD_MIO34: tslots::BEL,
    IOPAD_MIO35: tslots::BEL,
    IOPAD_MIO36: tslots::BEL,
    IOPAD_MIO37: tslots::BEL,
    IOPAD_MIO38: tslots::BEL,
    IOPAD_MIO39: tslots::BEL,
    IOPAD_MIO40: tslots::BEL,
    IOPAD_MIO41: tslots::BEL,
    IOPAD_MIO42: tslots::BEL,
    IOPAD_MIO43: tslots::BEL,
    IOPAD_MIO44: tslots::BEL,
    IOPAD_MIO45: tslots::BEL,
    IOPAD_MIO46: tslots::BEL,
    IOPAD_MIO47: tslots::BEL,
    IOPAD_MIO48: tslots::BEL,
    IOPAD_MIO49: tslots::BEL,
    IOPAD_MIO50: tslots::BEL,
    IOPAD_MIO51: tslots::BEL,
    IOPAD_MIO52: tslots::BEL,
    IOPAD_MIO53: tslots::BEL,
    IOPAD_DDRODT: tslots::BEL,
    IOPAD_PSPORB: tslots::BEL,
    IOPAD_DDRRASB: tslots::BEL,
    IOPAD_PSSRSTB: tslots::BEL,
];

pub const SLICE: [BelSlotId; 4] = [SLICE0, SLICE1, SLICE2, SLICE3];
pub const BRAM_H: [BelSlotId; 2] = [BRAM_H0, BRAM_H1];
pub const DSP: [BelSlotId; 2] = [DSP0, DSP1];

pub const ILOGIC: [BelSlotId; 2] = [ILOGIC0, ILOGIC1];
pub const OLOGIC: [BelSlotId; 2] = [OLOGIC0, OLOGIC1];
pub const IODELAY: [BelSlotId; 2] = [IODELAY0, IODELAY1];
pub const IDELAY: [BelSlotId; 2] = [IDELAY0, IDELAY1];
pub const ODELAY: [BelSlotId; 2] = [ODELAY0, ODELAY1];
pub const IOB: [BelSlotId; 2] = [IOB0, IOB1];

pub const DCM: [BelSlotId; 2] = [DCM0, DCM1];

pub const MMCM: [BelSlotId; 2] = [MMCM0, MMCM1];

pub const PMCD: [BelSlotId; 2] = [PMCD0, PMCD1];

pub const BUFGCTRL: [BelSlotId; 32] = [
    BUFGCTRL0, BUFGCTRL1, BUFGCTRL2, BUFGCTRL3, BUFGCTRL4, BUFGCTRL5, BUFGCTRL6, BUFGCTRL7,
    BUFGCTRL8, BUFGCTRL9, BUFGCTRL10, BUFGCTRL11, BUFGCTRL12, BUFGCTRL13, BUFGCTRL14, BUFGCTRL15,
    BUFGCTRL16, BUFGCTRL17, BUFGCTRL18, BUFGCTRL19, BUFGCTRL20, BUFGCTRL21, BUFGCTRL22, BUFGCTRL23,
    BUFGCTRL24, BUFGCTRL25, BUFGCTRL26, BUFGCTRL27, BUFGCTRL28, BUFGCTRL29, BUFGCTRL30, BUFGCTRL31,
];

pub const BUFHCE_W: [BelSlotId; 12] = [
    BUFHCE_W0, BUFHCE_W1, BUFHCE_W2, BUFHCE_W3, BUFHCE_W4, BUFHCE_W5, BUFHCE_W6, BUFHCE_W7,
    BUFHCE_W8, BUFHCE_W9, BUFHCE_W10, BUFHCE_W11,
];

pub const BUFHCE_E: [BelSlotId; 12] = [
    BUFHCE_E0, BUFHCE_E1, BUFHCE_E2, BUFHCE_E3, BUFHCE_E4, BUFHCE_E5, BUFHCE_E6, BUFHCE_E7,
    BUFHCE_E8, BUFHCE_E9, BUFHCE_E10, BUFHCE_E11,
];

pub const BUFIO: [BelSlotId; 4] = [BUFIO0, BUFIO1, BUFIO2, BUFIO3];
pub const BUFR: [BelSlotId; 4] = [BUFR0, BUFR1, BUFR2, BUFR3];
pub const BUFO: [BelSlotId; 2] = [BUFO0, BUFO1];

pub const PHASER_IN: [BelSlotId; 4] = [PHASER_IN0, PHASER_IN1, PHASER_IN2, PHASER_IN3];
pub const PHASER_OUT: [BelSlotId; 4] = [PHASER_OUT0, PHASER_OUT1, PHASER_OUT2, PHASER_OUT3];

pub const BUFMRCE: [BelSlotId; 2] = [BUFMRCE0, BUFMRCE1];

pub const BSCAN: [BelSlotId; 4] = [BSCAN0, BSCAN1, BSCAN2, BSCAN3];

pub const ICAP: [BelSlotId; 2] = [ICAP0, ICAP1];
pub const PMV: [BelSlotId; 2] = [PMV0, PMV1];

pub const BUFDS: [BelSlotId; 2] = [BUFDS0, BUFDS1];
pub const GT11: [BelSlotId; 2] = [GT11_0, GT11_1];
pub const GTX: [BelSlotId; 4] = [GTX0, GTX1, GTX2, GTX3];
pub const CRC32: [BelSlotId; 4] = [CRC32_0, CRC32_1, CRC32_2, CRC32_3];
pub const CRC64: [BelSlotId; 2] = [CRC64_0, CRC64_1];

pub const IPAD_RXP: [BelSlotId; 4] = [IPAD_RXP0, IPAD_RXP1, IPAD_RXP2, IPAD_RXP3];
pub const IPAD_RXN: [BelSlotId; 4] = [IPAD_RXN0, IPAD_RXN1, IPAD_RXN2, IPAD_RXN3];
pub const OPAD_TXP: [BelSlotId; 4] = [OPAD_TXP0, OPAD_TXP1, OPAD_TXP2, OPAD_TXP3];
pub const OPAD_TXN: [BelSlotId; 4] = [OPAD_TXN0, OPAD_TXN1, OPAD_TXN2, OPAD_TXN3];

pub const GCLK_TEST_BUF_HROW_GCLK: [BelSlotId; 32] = [
    GCLK_TEST_BUF_HROW_GCLK0,
    GCLK_TEST_BUF_HROW_GCLK1,
    GCLK_TEST_BUF_HROW_GCLK2,
    GCLK_TEST_BUF_HROW_GCLK3,
    GCLK_TEST_BUF_HROW_GCLK4,
    GCLK_TEST_BUF_HROW_GCLK5,
    GCLK_TEST_BUF_HROW_GCLK6,
    GCLK_TEST_BUF_HROW_GCLK7,
    GCLK_TEST_BUF_HROW_GCLK8,
    GCLK_TEST_BUF_HROW_GCLK9,
    GCLK_TEST_BUF_HROW_GCLK10,
    GCLK_TEST_BUF_HROW_GCLK11,
    GCLK_TEST_BUF_HROW_GCLK12,
    GCLK_TEST_BUF_HROW_GCLK13,
    GCLK_TEST_BUF_HROW_GCLK14,
    GCLK_TEST_BUF_HROW_GCLK15,
    GCLK_TEST_BUF_HROW_GCLK16,
    GCLK_TEST_BUF_HROW_GCLK17,
    GCLK_TEST_BUF_HROW_GCLK18,
    GCLK_TEST_BUF_HROW_GCLK19,
    GCLK_TEST_BUF_HROW_GCLK20,
    GCLK_TEST_BUF_HROW_GCLK21,
    GCLK_TEST_BUF_HROW_GCLK22,
    GCLK_TEST_BUF_HROW_GCLK23,
    GCLK_TEST_BUF_HROW_GCLK24,
    GCLK_TEST_BUF_HROW_GCLK25,
    GCLK_TEST_BUF_HROW_GCLK26,
    GCLK_TEST_BUF_HROW_GCLK27,
    GCLK_TEST_BUF_HROW_GCLK28,
    GCLK_TEST_BUF_HROW_GCLK29,
    GCLK_TEST_BUF_HROW_GCLK30,
    GCLK_TEST_BUF_HROW_GCLK31,
];

pub const GCLK_TEST_BUF_REBUF_S: [BelSlotId; 16] = [
    GCLK_TEST_BUF_REBUF_S0,
    GCLK_TEST_BUF_REBUF_S1,
    GCLK_TEST_BUF_REBUF_S2,
    GCLK_TEST_BUF_REBUF_S3,
    GCLK_TEST_BUF_REBUF_S4,
    GCLK_TEST_BUF_REBUF_S5,
    GCLK_TEST_BUF_REBUF_S6,
    GCLK_TEST_BUF_REBUF_S7,
    GCLK_TEST_BUF_REBUF_S8,
    GCLK_TEST_BUF_REBUF_S9,
    GCLK_TEST_BUF_REBUF_S10,
    GCLK_TEST_BUF_REBUF_S11,
    GCLK_TEST_BUF_REBUF_S12,
    GCLK_TEST_BUF_REBUF_S13,
    GCLK_TEST_BUF_REBUF_S14,
    GCLK_TEST_BUF_REBUF_S15,
];

pub const GCLK_TEST_BUF_REBUF_N: [BelSlotId; 16] = [
    GCLK_TEST_BUF_REBUF_N0,
    GCLK_TEST_BUF_REBUF_N1,
    GCLK_TEST_BUF_REBUF_N2,
    GCLK_TEST_BUF_REBUF_N3,
    GCLK_TEST_BUF_REBUF_N4,
    GCLK_TEST_BUF_REBUF_N5,
    GCLK_TEST_BUF_REBUF_N6,
    GCLK_TEST_BUF_REBUF_N7,
    GCLK_TEST_BUF_REBUF_N8,
    GCLK_TEST_BUF_REBUF_N9,
    GCLK_TEST_BUF_REBUF_N10,
    GCLK_TEST_BUF_REBUF_N11,
    GCLK_TEST_BUF_REBUF_N12,
    GCLK_TEST_BUF_REBUF_N13,
    GCLK_TEST_BUF_REBUF_N14,
    GCLK_TEST_BUF_REBUF_N15,
];

pub const IOPAD_DDRA: [BelSlotId; 15] = [
    IOPAD_DDRA0,
    IOPAD_DDRA1,
    IOPAD_DDRA2,
    IOPAD_DDRA3,
    IOPAD_DDRA4,
    IOPAD_DDRA5,
    IOPAD_DDRA6,
    IOPAD_DDRA7,
    IOPAD_DDRA8,
    IOPAD_DDRA9,
    IOPAD_DDRA10,
    IOPAD_DDRA11,
    IOPAD_DDRA12,
    IOPAD_DDRA13,
    IOPAD_DDRA14,
];

pub const IOPAD_DDRBA: [BelSlotId; 3] = [IOPAD_DDRBA0, IOPAD_DDRBA1, IOPAD_DDRBA2];

pub const IOPAD_DDRDM: [BelSlotId; 4] = [IOPAD_DDRDM0, IOPAD_DDRDM1, IOPAD_DDRDM2, IOPAD_DDRDM3];

pub const IOPAD_DDRDQSP: [BelSlotId; 4] = [
    IOPAD_DDRDQSP0,
    IOPAD_DDRDQSP1,
    IOPAD_DDRDQSP2,
    IOPAD_DDRDQSP3,
];

pub const IOPAD_DDRDQSN: [BelSlotId; 4] = [
    IOPAD_DDRDQSN0,
    IOPAD_DDRDQSN1,
    IOPAD_DDRDQSN2,
    IOPAD_DDRDQSN3,
];

pub const IOPAD_DDRDQ: [BelSlotId; 32] = [
    IOPAD_DDRDQ0,
    IOPAD_DDRDQ1,
    IOPAD_DDRDQ2,
    IOPAD_DDRDQ3,
    IOPAD_DDRDQ4,
    IOPAD_DDRDQ5,
    IOPAD_DDRDQ6,
    IOPAD_DDRDQ7,
    IOPAD_DDRDQ8,
    IOPAD_DDRDQ9,
    IOPAD_DDRDQ10,
    IOPAD_DDRDQ11,
    IOPAD_DDRDQ12,
    IOPAD_DDRDQ13,
    IOPAD_DDRDQ14,
    IOPAD_DDRDQ15,
    IOPAD_DDRDQ16,
    IOPAD_DDRDQ17,
    IOPAD_DDRDQ18,
    IOPAD_DDRDQ19,
    IOPAD_DDRDQ20,
    IOPAD_DDRDQ21,
    IOPAD_DDRDQ22,
    IOPAD_DDRDQ23,
    IOPAD_DDRDQ24,
    IOPAD_DDRDQ25,
    IOPAD_DDRDQ26,
    IOPAD_DDRDQ27,
    IOPAD_DDRDQ28,
    IOPAD_DDRDQ29,
    IOPAD_DDRDQ30,
    IOPAD_DDRDQ31,
];

pub const IOPAD_MIO: [BelSlotId; 54] = [
    IOPAD_MIO0,
    IOPAD_MIO1,
    IOPAD_MIO2,
    IOPAD_MIO3,
    IOPAD_MIO4,
    IOPAD_MIO5,
    IOPAD_MIO6,
    IOPAD_MIO7,
    IOPAD_MIO8,
    IOPAD_MIO9,
    IOPAD_MIO10,
    IOPAD_MIO11,
    IOPAD_MIO12,
    IOPAD_MIO13,
    IOPAD_MIO14,
    IOPAD_MIO15,
    IOPAD_MIO16,
    IOPAD_MIO17,
    IOPAD_MIO18,
    IOPAD_MIO19,
    IOPAD_MIO20,
    IOPAD_MIO21,
    IOPAD_MIO22,
    IOPAD_MIO23,
    IOPAD_MIO24,
    IOPAD_MIO25,
    IOPAD_MIO26,
    IOPAD_MIO27,
    IOPAD_MIO28,
    IOPAD_MIO29,
    IOPAD_MIO30,
    IOPAD_MIO31,
    IOPAD_MIO32,
    IOPAD_MIO33,
    IOPAD_MIO34,
    IOPAD_MIO35,
    IOPAD_MIO36,
    IOPAD_MIO37,
    IOPAD_MIO38,
    IOPAD_MIO39,
    IOPAD_MIO40,
    IOPAD_MIO41,
    IOPAD_MIO42,
    IOPAD_MIO43,
    IOPAD_MIO44,
    IOPAD_MIO45,
    IOPAD_MIO46,
    IOPAD_MIO47,
    IOPAD_MIO48,
    IOPAD_MIO49,
    IOPAD_MIO50,
    IOPAD_MIO51,
    IOPAD_MIO52,
    IOPAD_MIO53,
];
