use prjcombine_interconnect::{bels, db::BelSlotId};

use crate::tslots;

bels![
    INT: tslots::INT,
    RLL: tslots::INT,
    INTF_TESTMUX: tslots::INTF,
    CLK_INT: tslots::CLK,
    TERM_W: tslots::TERM_H,
    TERM_E: tslots::TERM_H,
    TERM_S: tslots::TERM_V,
    TERM_N: tslots::TERM_V,
    PPC_TERM_W: tslots::TERM_H,
    PPC_TERM_E: tslots::TERM_H,
    PPC_TERM_S: tslots::TERM_V,
    PPC_TERM_N: tslots::TERM_V,
    LLH: tslots::TERM_H,
    LLV: tslots::TERM_V,
    SLICE0: tslots::BEL,
    SLICE1: tslots::BEL,
    SLICE2: tslots::BEL,
    SLICE3: tslots::BEL,
    TBUF0: tslots::BEL,
    TBUF1: tslots::BEL,
    TBUS: tslots::BEL,
    IO0: tslots::BEL,
    IO1: tslots::BEL,
    IO2: tslots::BEL,
    IO3: tslots::BEL,
    IBUF0: tslots::BEL,
    IBUF1: tslots::BEL,
    IBUF2: tslots::BEL,
    IBUF3: tslots::BEL,
    OBUF0: tslots::BEL,
    OBUF1: tslots::BEL,
    OBUF2: tslots::BEL,
    OBUF3: tslots::BEL,
    BRAM: tslots::BEL,
    MULT: tslots::BEL,
    DSP: tslots::BEL,
    DCM: tslots::BEL,
    GT: tslots::BEL,
    GT10: tslots::BEL,
    IPAD_RXP: tslots::BEL,
    IPAD_RXN: tslots::BEL,
    OPAD_TXP: tslots::BEL,
    OPAD_TXN: tslots::BEL,
    PPC405: tslots::BEL,
    DCI0: tslots::BEL,
    DCI1: tslots::BEL,
    DCIRESET0: tslots::BEL,
    DCIRESET1: tslots::BEL,
    STARTUP: tslots::BEL,
    CAPTURE: tslots::BEL,
    ICAP: tslots::BEL,
    SPI_ACCESS: tslots::BEL,
    PMV: tslots::BEL,
    DNA_PORT: tslots::BEL,
    BSCAN: tslots::BEL,
    JTAGPPC: tslots::BEL,
    BUFGMUX0: tslots::CLK,
    BUFGMUX1: tslots::CLK,
    BUFGMUX2: tslots::CLK,
    BUFGMUX3: tslots::CLK,
    BUFGMUX4: tslots::CLK,
    BUFGMUX5: tslots::CLK,
    BUFGMUX6: tslots::CLK,
    BUFGMUX7: tslots::CLK,
    PCILOGIC: tslots::CLK,
    PCILOGICSE: tslots::CLK,
    VCC: tslots::CLK,
    GLOBALSIG_S0: tslots::CLK,
    GLOBALSIG_S1: tslots::CLK,
    GLOBALSIG_N0: tslots::CLK,
    GLOBALSIG_N1: tslots::CLK,
    GLOBALSIG_S: tslots::CLK,
    GLOBALSIG_N: tslots::CLK,
    GLOBALSIG_WE: tslots::CLK,
    DCMCONN: tslots::CLK,
    DCMCONN_S3E: tslots::BEL,
    BREFCLK_INT: tslots::BEL,
    BREFCLK: tslots::CLK,
    CLKC: tslots::CLK,
    CLKC_50A: tslots::CLK,
    GCLKC: tslots::HROW,
    GCLKH: tslots::HCLK,
    GCLKVM: tslots::CLK,
    GCLKVC: tslots::HROW,
    GLOBALSIG: tslots::HCLK,
    GLOBALSIG_DSP: tslots::CLK,
    PTE2OMUX0: tslots::INT,
    PTE2OMUX1: tslots::INT,
    PTE2OMUX2: tslots::INT,
    PTE2OMUX3: tslots::INT,
    RANDOR: tslots::RANDOR,
    RANDOR_OUT: tslots::BEL,
    PCI_CE_N: tslots::PCI_CE,
    PCI_CE_S: tslots::PCI_CE,
    PCI_CE_W: tslots::PCI_CE,
    PCI_CE_E: tslots::PCI_CE,
    PCI_CE_CNR: tslots::PCI_CE,
    MISR: tslots::BEL,
];

pub const SLICE: [BelSlotId; 4] = [SLICE0, SLICE1, SLICE2, SLICE3];

pub const TBUF: [BelSlotId; 2] = [TBUF0, TBUF1];
pub const IO: [BelSlotId; 4] = [IO0, IO1, IO2, IO3];
pub const IBUF: [BelSlotId; 4] = [IBUF0, IBUF1, IBUF2, IBUF3];
pub const OBUF: [BelSlotId; 4] = [OBUF0, OBUF1, OBUF2, OBUF3];
pub const BUFGMUX: [BelSlotId; 8] = [
    BUFGMUX0, BUFGMUX1, BUFGMUX2, BUFGMUX3, BUFGMUX4, BUFGMUX5, BUFGMUX6, BUFGMUX7,
];
pub const PTE2OMUX: [BelSlotId; 4] = [PTE2OMUX0, PTE2OMUX1, PTE2OMUX2, PTE2OMUX3];
