use prjcombine_interconnect::{bels, db::BelSlotId};

bels![
    RLL,
    SLICE0,
    SLICE1,
    SLICE2,
    SLICE3,
    TBUF0,
    TBUF1,
    TBUS,
    IO0,
    IO1,
    IO2,
    IO3,
    IBUF0,
    IBUF1,
    IBUF2,
    IBUF3,
    OBUF0,
    OBUF1,
    OBUF2,
    OBUF3,
    BRAM,
    MULT,
    DSP,
    DCM,
    GT,
    GT10,
    IPAD_RXP,
    IPAD_RXN,
    OPAD_TXP,
    OPAD_TXN,
    PPC405,
    DCI0,
    DCI1,
    DCIRESET0,
    DCIRESET1,
    STARTUP,
    CAPTURE,
    ICAP,
    SPI_ACCESS,
    PMV,
    DNA_PORT,
    BSCAN,
    JTAGPPC,
    BUFGMUX0,
    BUFGMUX1,
    BUFGMUX2,
    BUFGMUX3,
    BUFGMUX4,
    BUFGMUX5,
    BUFGMUX6,
    BUFGMUX7,
    PCILOGIC,
    PCILOGICSE,
    VCC,
    GLOBALSIG_S0,
    GLOBALSIG_S1,
    GLOBALSIG_N0,
    GLOBALSIG_N1,
    GLOBALSIG_S,
    GLOBALSIG_N,
    GLOBALSIG_WE,
    DCMCONN,
    DCMCONN_S3E,
    BREFCLK_INT,
    BREFCLK,
    CLKC,
    CLKC_50A,
    GCLKC,
    GCLKH,
    GCLKVM,
    GCLKVC,
    GLOBALSIG,
    GLOBALSIG_DSP,
    PTE2OMUX0,
    PTE2OMUX1,
    PTE2OMUX2,
    PTE2OMUX3,
    RANDOR,
    RANDOR_OUT,
    PCI_CE_N,
    PCI_CE_S,
    PCI_CE_W,
    PCI_CE_E,
    PCI_CE_CNR,
    MISR,
];

pub const SLICE: [BelSlotId; 4] = [SLICE0, SLICE1, SLICE2, SLICE3];

pub const TBUF: [BelSlotId; 2] = [TBUF0, TBUF1];
pub const IO: [BelSlotId; 4] = [IO0, IO1, IO2, IO3];
pub const IBUF: [BelSlotId; 4] = [IBUF0, IBUF1, IBUF2, IBUF3];
pub const OBUF: [BelSlotId; 4] = [OBUF0, OBUF1, OBUF2, OBUF3];
pub const BUFGMUX: [BelSlotId; 8] = [
    BUFGMUX0, BUFGMUX1, BUFGMUX2, BUFGMUX3, BUFGMUX4, BUFGMUX5, BUFGMUX6, BUFGMUX7,
];
pub const PTE2OMUX: [BelSlotId; 4] = [PTE2OMUX0, PTE2OMUX1, PTE2OMUX2, PTE2OMUX3];
