use prjcombine_interconnect::{bels, db::BelSlotId};

use crate::tslots;

bels![
    INT: tslots::INT,
    REG_INT: tslots::REG,
    SLICE0: tslots::BEL,
    SLICE1: tslots::BEL,
    BRAM_F: tslots::BEL,
    BRAM_H0: tslots::BEL,
    BRAM_H1: tslots::BEL,
    DSP: tslots::BEL,
    ILOGIC0: tslots::BEL,
    ILOGIC1: tslots::BEL,
    OLOGIC0: tslots::BEL,
    OLOGIC1: tslots::BEL,
    IODELAY0: tslots::BEL,
    IODELAY1: tslots::BEL,
    IOB0: tslots::IOB,
    IOB1: tslots::IOB,
    IOICLK0: tslots::BEL,
    IOICLK1: tslots::BEL,
    IOI: tslots::BEL,
    DCM0: tslots::BEL,
    DCM1: tslots::BEL,
    PLL: tslots::BEL,
    CMT: tslots::BEL,
    DCM_BUFPLL_BUF_S: tslots::CMT_BUF,
    DCM_BUFPLL_BUF_S_MID: tslots::CMT_BUF,
    DCM_BUFPLL_BUF_N: tslots::CMT_BUF,
    DCM_BUFPLL_BUF_N_MID: tslots::CMT_BUF,
    PLL_BUFPLL: tslots::CMT_BUF,
    MCB: tslots::BEL,
    PCIE: tslots::BEL,
    GTP: tslots::BEL,
    BUFDS0: tslots::BEL,
    BUFDS1: tslots::BEL,
    PCILOGICSE: tslots::BEL,
    OCT_CAL0: tslots::BEL,
    OCT_CAL1: tslots::BEL,
    OCT_CAL2: tslots::BEL,
    OCT_CAL3: tslots::BEL,
    OCT_CAL4: tslots::BEL,
    OCT_CAL5: tslots::BEL,
    PMV: tslots::BEL,
    DNA_PORT: tslots::BEL,
    ICAP: tslots::BEL,
    SPI_ACCESS: tslots::BEL,
    SUSPEND_SYNC: tslots::BEL,
    POST_CRC_INTERNAL: tslots::BEL,
    STARTUP: tslots::BEL,
    SLAVE_SPI: tslots::BEL,
    BSCAN0: tslots::BEL,
    BSCAN1: tslots::BEL,
    BSCAN2: tslots::BEL,
    BSCAN3: tslots::BEL,
    HCLK: tslots::HCLK,
    BUFH_W0: tslots::HCLK_ROW,
    BUFH_W1: tslots::HCLK_ROW,
    BUFH_W2: tslots::HCLK_ROW,
    BUFH_W3: tslots::HCLK_ROW,
    BUFH_W4: tslots::HCLK_ROW,
    BUFH_W5: tslots::HCLK_ROW,
    BUFH_W6: tslots::HCLK_ROW,
    BUFH_W7: tslots::HCLK_ROW,
    BUFH_W8: tslots::HCLK_ROW,
    BUFH_W9: tslots::HCLK_ROW,
    BUFH_W10: tslots::HCLK_ROW,
    BUFH_W11: tslots::HCLK_ROW,
    BUFH_W12: tslots::HCLK_ROW,
    BUFH_W13: tslots::HCLK_ROW,
    BUFH_W14: tslots::HCLK_ROW,
    BUFH_W15: tslots::HCLK_ROW,
    BUFH_E0: tslots::HCLK_ROW,
    BUFH_E1: tslots::HCLK_ROW,
    BUFH_E2: tslots::HCLK_ROW,
    BUFH_E3: tslots::HCLK_ROW,
    BUFH_E4: tslots::HCLK_ROW,
    BUFH_E5: tslots::HCLK_ROW,
    BUFH_E6: tslots::HCLK_ROW,
    BUFH_E7: tslots::HCLK_ROW,
    BUFH_E8: tslots::HCLK_ROW,
    BUFH_E9: tslots::HCLK_ROW,
    BUFH_E10: tslots::HCLK_ROW,
    BUFH_E11: tslots::HCLK_ROW,
    BUFH_E12: tslots::HCLK_ROW,
    BUFH_E13: tslots::HCLK_ROW,
    BUFH_E14: tslots::HCLK_ROW,
    BUFH_E15: tslots::HCLK_ROW,
    HCLK_ROW: tslots::HCLK_ROW,
    BUFGMUX0: tslots::BEL,
    BUFGMUX1: tslots::BEL,
    BUFGMUX2: tslots::BEL,
    BUFGMUX3: tslots::BEL,
    BUFGMUX4: tslots::BEL,
    BUFGMUX5: tslots::BEL,
    BUFGMUX6: tslots::BEL,
    BUFGMUX7: tslots::BEL,
    BUFGMUX8: tslots::BEL,
    BUFGMUX9: tslots::BEL,
    BUFGMUX10: tslots::BEL,
    BUFGMUX11: tslots::BEL,
    BUFGMUX12: tslots::BEL,
    BUFGMUX13: tslots::BEL,
    BUFGMUX14: tslots::BEL,
    BUFGMUX15: tslots::BEL,
    CLKC: tslots::BEL,
    CLKC_BUFPLL: tslots::BEL,
    BUFIO2_0: tslots::REG,
    BUFIO2_1: tslots::REG,
    BUFIO2_2: tslots::REG,
    BUFIO2_3: tslots::REG,
    BUFIO2_4: tslots::REG,
    BUFIO2_5: tslots::REG,
    BUFIO2_6: tslots::REG,
    BUFIO2_7: tslots::REG,
    BUFIO2FB_0: tslots::REG,
    BUFIO2FB_1: tslots::REG,
    BUFIO2FB_2: tslots::REG,
    BUFIO2FB_3: tslots::REG,
    BUFIO2FB_4: tslots::REG,
    BUFIO2FB_5: tslots::REG,
    BUFIO2FB_6: tslots::REG,
    BUFIO2FB_7: tslots::REG,
    BUFPLL0: tslots::REG,
    BUFPLL1: tslots::REG,
    BUFPLL_MCB: tslots::REG,
    BUFPLL_OUT: tslots::REG,
    BUFPLL_INS_LR: tslots::REG,
    BUFPLL_INS_BT: tslots::REG,
    // RE-only detritus?
    BTIOI_CLK: tslots::IOI_CLK,
    LRIOI_CLK: tslots::IOI_CLK,
    LRIOI_CLK_TERM: tslots::IOI_CLK,
    PCI_CE_TRUNK_BUF: tslots::PCI_CE_TRUNK_BUF,
    PCI_CE_V_BUF: tslots::PCI_CE_BUF,
    PCI_CE_H_BUF: tslots::PCI_CE_BUF,
    PCI_CE_SPLIT: tslots::PCI_CE_BUF,
    HCLK_V_MIDBUF: tslots::CLK_BUF,
    CKPIN_V_MIDBUF: tslots::CLK_BUF,
    CKPIN_H_MIDBUF: tslots::CLK_BUF,
    HCLK_H_MIDBUF: tslots::CLK_BUF,
    BUFIO2_INS: tslots::REG,
    BUFIO2_CKPIN: tslots::REG,
    BUFPLL_BUF: tslots::REG,
    CLKPIN_BUF: tslots::CLK_BUF,
    GTP_H_BUF: tslots::REG,
    MCB_TIE_CLK: tslots::BEL,
    MCB_TIE_DQS0: tslots::BEL,
    MCB_TIE_DQS1: tslots::BEL,
    TIEOFF_IOI: tslots::BEL,
    TIEOFF_REG: tslots::REG,
    TIEOFF_PLL: tslots::BEL,
    TIEOFF_CLK: tslots::BEL,
    TIEOFF_DQS0: tslots::BEL,
    TIEOFF_DQS1: tslots::BEL,
    IPAD_RXP0: tslots::BEL,
    IPAD_RXN0: tslots::BEL,
    IPAD_RXP1: tslots::BEL,
    IPAD_RXN1: tslots::BEL,
    IPAD_CLKP0: tslots::BEL,
    IPAD_CLKN0: tslots::BEL,
    IPAD_CLKP1: tslots::BEL,
    IPAD_CLKN1: tslots::BEL,
    OPAD_TXP0: tslots::BEL,
    OPAD_TXN0: tslots::BEL,
    OPAD_TXP1: tslots::BEL,
    OPAD_TXN1: tslots::BEL,
    GTP_BUF: tslots::BEL,
];

pub const SLICE: [BelSlotId; 2] = [SLICE0, SLICE1];
pub const ILOGIC: [BelSlotId; 2] = [ILOGIC0, ILOGIC1];
pub const OLOGIC: [BelSlotId; 2] = [OLOGIC0, OLOGIC1];
pub const IODELAY: [BelSlotId; 2] = [IODELAY0, IODELAY1];
pub const IOICLK: [BelSlotId; 2] = [IOICLK0, IOICLK1];
pub const IOB: [BelSlotId; 2] = [IOB0, IOB1];
pub const DCM: [BelSlotId; 2] = [DCM0, DCM1];
pub const BUFIO2: [BelSlotId; 8] = [
    BUFIO2_0, BUFIO2_1, BUFIO2_2, BUFIO2_3, BUFIO2_4, BUFIO2_5, BUFIO2_6, BUFIO2_7,
];
pub const BUFIO2FB: [BelSlotId; 8] = [
    BUFIO2FB_0, BUFIO2FB_1, BUFIO2FB_2, BUFIO2FB_3, BUFIO2FB_4, BUFIO2FB_5, BUFIO2FB_6, BUFIO2FB_7,
];
pub const BUFPLL: [BelSlotId; 2] = [BUFPLL0, BUFPLL1];
pub const BUFDS: [BelSlotId; 2] = [BUFDS0, BUFDS1];
pub const BUFH_W: [BelSlotId; 16] = [
    BUFH_W0, BUFH_W1, BUFH_W2, BUFH_W3, BUFH_W4, BUFH_W5, BUFH_W6, BUFH_W7, BUFH_W8, BUFH_W9,
    BUFH_W10, BUFH_W11, BUFH_W12, BUFH_W13, BUFH_W14, BUFH_W15,
];
pub const BUFH_E: [BelSlotId; 16] = [
    BUFH_E0, BUFH_E1, BUFH_E2, BUFH_E3, BUFH_E4, BUFH_E5, BUFH_E6, BUFH_E7, BUFH_E8, BUFH_E9,
    BUFH_E10, BUFH_E11, BUFH_E12, BUFH_E13, BUFH_E14, BUFH_E15,
];
pub const BUFGMUX: [BelSlotId; 16] = [
    BUFGMUX0, BUFGMUX1, BUFGMUX2, BUFGMUX3, BUFGMUX4, BUFGMUX5, BUFGMUX6, BUFGMUX7, BUFGMUX8,
    BUFGMUX9, BUFGMUX10, BUFGMUX11, BUFGMUX12, BUFGMUX13, BUFGMUX14, BUFGMUX15,
];
pub const BSCAN: [BelSlotId; 4] = [BSCAN0, BSCAN1, BSCAN2, BSCAN3];
