use prjcombine_re_fpga_hammer::specials;

specials![
    // xc2000
    CLB_MODE_F,
    CLB_MODE_FG,
    CLB_MODE_FGM,
    CLB_LUT_ABC,
    CLB_LUT_ABD,
    CLB_LUT_ACD,
    CLB_LUT_BCD,
    CLB_LUT_ABQ,
    CLB_LUT_ACQ,
    CLB_LUT_BCQ,
    CLB_LUT_MACD,
    CLB_LUT_EQ_ABC,
    CLB_LUT_EQ_BCD,
    CLB_LUT_EQ_BCQ,
    CLB_LUT_EQ_ABCD,
    CLB_MUX_XY_M,
    CLB_CLK_C,
    CLB_CLK_G,
    IO_BUF_ON,
    IO_IQ,
    BIDI_S,

    // xc3000
    CLB_LUT_ABCD,
    CLB_LUT_ABCE,
    CLB_LUT_AQXCD,
    CLB_LUT_AQYCD,
    CLB_LUT_ABQXD,
    CLB_LUT_ABQYD,
    CLB_LUT_ABCDE,
    CLB_LUT_EQ_ABCE,
    CLB_LUT_EQ_AQXCD,
    CLB_LUT_EQ_AQYCD,
    CLB_LUT_EQ_ABQXD,
    CLB_LUT_EQ_ABQYD,
    CLB_LUT_EQ_ABCDE,
    CLB_M,
    CLB_CLK,
    IO_IN_I,
    IO_IN_PULLUP,
    IO_OUT_O,
];
