on:
  push:
  pull_request:
  merge_group:

name: CI
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up mdBook
        uses: peaceiris/actions-mdbook@v2
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build the book
        run: |
          mdbook build docs
      - name: Upload documentation archive
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/book

  publish:
    needs: document
    if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Download documentation archive
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/book
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: pages
          folder: docs/book/
